"""add_job_company_id

Revision ID: 94ac3793f07a
Revises: f42ccfff1dc1
Create Date: 2026-06-12 18:46:31.619329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94ac3793f07a'
down_revision: Union[str, Sequence[str], None] = 'f42ccfff1dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add column as nullable at first
    op.add_column('jobs', sa.Column('company_id', sa.String(length=36), nullable=True))
    
    # 2. Insert a default company to associate with existing jobs
    op.execute("""
        INSERT INTO companies (id, name, created_at)
        VALUES ('default-company-id', 'Default Company', NOW())
        ON CONFLICT (id) DO NOTHING
    """)
    
    # 3. Update existing jobs to use the default company ID
    op.execute("UPDATE jobs SET company_id = 'default-company-id' WHERE company_id IS NULL")
    
    # 4. Alter column to be NOT NULL
    op.alter_column('jobs', 'company_id', nullable=False)
    
    # 5. Create foreign key constraint
    op.create_foreign_key(None, 'jobs', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'company_id')
    # ### end Alembic commands ###
